### ISSUE TITLE
Berenson Art Collection: artworks

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/pharos-mappings#131]
Are we sure the records from the Berenson Art Collection have been imported? This is all I get when I search for artworks kept at I Tatti
https://artresearch.net/resource/?uri=Default%3ASearch3&semanticSearch=N4IgziBcoCYPZRAHgBYBc0AcyQPS8xQEMAnOMAOlLRIFMxbSBjFCgO1rVzrDgFcSTWrgBmTXAHc4JANYA%2BEABoQTKAG1QdKJqKJUGbHgLEylaj0aDWHLj36DhY3AEs2YNM7R8PcNguVakMjoWDj4hKTkVCQ09JYs7Jzc9PZCoiS4AOrSMgD6MrSYaLkARgCeuQCSbh5ePn5KIDDqaiAASikCQkqgziTO2iAAKoiV-Y0AaoNotCQAtkNlmLSIAHJEc7Qwq3AwK8oAbkQANnwrQSGYRgdwTEQlFADmnGhlFFt8uHzHRGy4AKwABkBAGZAf8AEwATgA7CAAL7w5Q-Eq0Y6ICbOY4-AAElRxQyIGAGyj2YCY-SKzl8GKxuPxhOJjS8mGO51AYD4j2e7mpbEGIyCYxJICm0BAM3mi2Waw2Wx2e0aR1O5xAl2ut3uTxebw%2BXx%2BfyBoPB0LhiOR9zRAsQABlPLMTpNprMFktVXbJY7DiczrTsUQ8QSiR5GjAiUS3daheNlGLQJLXTKgutNttdvsQMrfRcDEYJPmKBIQRRpI9cBDgQBGXAADQAsjaAMosWhzIgAYnc-TYjwRSJABsefCIz0QfcRAF0J-2%2BGxnABHM6VZqQQHw6fKETqCcBejfNDafthtBEBhoCCQNQ7kAnZyPNibNgH8WCkAAEXDFDrRDKqKd0HNEBHhIIhCGbOBlkbeIUCjd9P2-X8MzjRF4SAA

**Comment by mafragias** [comment]
That is because of the search query : instead of kept by, I used has provider and returned 78722 matches
https://artresearch.net/resource/?uri=Default%3ASearch3&semanticSearch=N4IgziBcoCYPZRAHgBYBc0AcyQPS8xQEMAnOMAOlLRIFMxbSBjFCgO1rVzrDgFcSTWrgBmTXAHc4JANYA%2BEABoQTKAG1QdKJqKJUGbHgLEylaj0aDWHLj36DhY3AEs2YNM7R8PcNguVakMjoWDj4hKTkVCQ09JYs7Jzc9PZCoiS4AOrSMgD6xGC5mGQAbs4wtCS5AJJuHl4%2BfkogMOpqIABKKQJCSqDOJM7aIAAqiNWDzQBqw2iVALYjAJ6YtIgAckTztDDrcBXNJUQANnxrQSGG4SZR5nHM1kl2PcKeRBjOuLwvuNUj7x4QABfIHKY5EABGtGO4wABP8Ps0KmAmINMI04QjAcovJhjudQGA%2BABzYn0DHQUbjSbKGaUuYkRYrc4gTbbXb7NbKI6nFmXMLGSJmGIWB6JWzdBwuNAAz7fKV-WXA0EgcFQmGUsZBAAynkqJ2mswWy1WiF1DIN3JOZ0xSuUMHe72Zwy1IAmQ1pRsZJpZbJ2ewOVt5iEuRgk4YoEgAzBRpMTcAAmAAMSYAjLgABoAWW1AGUWLR5kQAMTuQZsYnKsFECt8IhkxDKkEAXWbKr4bGcAEcztVWpAk0C28oROpmwF6HxjmhtCqHTKGGgIJA1OOQCdnMS2Ns2DPNYgACKOihZohLKGG6Ag5TEkhEQj5uCrXPxFAuw-H0-nrkgOnAEFAkAA

**Comment by spykoulouris** [comment]
provider is when I Tatti owns the photographs and provides the images of the artworks
kept by is when I Tatti is the owner of the artworks (that is the artworks that we have here).

Not sure if I interpret well the two different terms of the structured query.

**Comment by MinadakisNikos** [comment]
@spyros do you mean that Berenson Art Collection physically holds the artworks right? How many are expected to be there?

**Comment by spykoulouris** [comment]
We use the term "Berenson Art Collection" informally. The official name of the artwork's repository is I Tatti - The Harvard University Center...... 
I think we talk about 338 work records
https://images.hollis.harvard.edu/primo-explore/search?query=any,contains,ber*&tab=default_tab&search_scope=HVD_BERART_IMG&vid=HVD_IMAGES&lang=en_US&offset=0

**Comment by mafragias** [comment]
@spykoulouris I looked a bit more into it and it seems that the issue comes from the faulty reconciliation of institutions.
I have already created an issue to refine the reconciliation of institutions at https://github.com/ArtResearch/pharos-mappings/issues/90

**Comment by MinadakisNikos** [comment]
great close it

**Comment by mafragias** [comment]
Issue validated
