### ISSUE TITLE
merged record KHI --> I Tatti

### ISSUE THREAD

**Issue by lklic** [ArtResearch/pharos-mappings#189]
It's unclear what this record is:
https://artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fpharos%2Fartwork%2F0493282467

**Comment by MinadakisNikos** [comment]
Problem still exists: https://dev.artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fpharos%2Fartwork%2F0493282467 @mafragias lets check tomorrow to see what is happening. A messing of ids? This is the first time that something like this happens

**Comment by MinadakisNikos** [comment]
@mafragias is this fixed? we said to include also the provider in the hashing of the id

**Comment by mafragias** [comment]
This is an outdated issue, since the hashes for the works are now lengthier, hence more unique. In addition the provider is also included in the generation of the has as @MinadakisNikos  explained.

hash example for pharos artworks : https://pharos.artresearch.net/resource/pharos/artwork/0e91b4b6b3da317d562759cf2b25f5670e84a127
