### ISSUE TITLE
GETTY dates are show twice

### ISSUE THREAD

**Issue by MinadakisNikos** [ArtResearch/pharos-mappings#204]
Getty dates show both year and fake year for example:
2007
2007-01-01
that is automaticall created for the timeline I guess?

only the actual year should be visible in artists templates

example:

https://artresearch.net/resource/?uri=http%3A%2F%2Fvocab.getty.edu%2Fulan%2F500015403

**Comment by AndreasMichelakis** [comment]
Relevant to this https://github.com/ArtResearch/pharos-dev/issues/228

**Comment by lklic** [comment]
Please take a look at this issue for how to format dates:
https://github.com/ArtResearch/pharos-dev/issues/184

I think the data should occur only once in the data and we should use handlebars/moment.js to reformat them: When we have Jan 1st or dec 31st we do not display the day/month, otherwise we do.

Jan 1st 1970 is a problem with unix date/time and should be copletely removed from the data programmatically, either at the transformation phase or through a post-ingestion phase.

**Comment by mafragias** [comment]
The reason for the dates having 01-01 every time is for it to have the type xsd:date, so that it can be searchable from the contextual search. Also the reason that is duplicate is because in one case is xsd:string and in the other is xsd:date

![image](https://user-images.githubusercontent.com/23557768/126120422-f3019468-c093-4036-b567-01ae67670aa7.png)

**Comment by mafragias** [comment]
This is is resolved : 
![image](https://user-images.githubusercontent.com/23557768/130625264-f1d32044-895c-4ab6-93f3-0d18b890f731.png)
