### ISSUE TITLE
michelangelo record

### ISSUE THREAD

**Issue by lklic** [ArtResearch/pharos-mappings#213]
simething has happened with this record:
https://artresearch.net/resource/?uri=http%3A%2F%2Fvocab.getty.edu%2Fulan%2F500010654

The name is split up into different parts, and michelangelo buonarotti is not searchable in the full text search.

**Comment by MinadakisNikos** [comment]
If I search for it I get back: https://artresearch.net/resource/?uri=http%3A%2F%2Fvocab.getty.edu%2Fulan%2F500010654 
did you expanded the list to see the alternative ids? Maybe we should limit the number of ids we take back from ulan, but I can search it and find it.

**Comment by mafragias** [comment]
> The name is split up into different parts, and michelangelo buonarotti is not searchable in the full text search.

Where exactly @lklic don't get back results for michelangelo buonarotti? Because I did the query "michelangelo buonarotti", in keyword search and I got back the record https://artresearch.net/resource/?uri=http%3A%2F%2Fvocab.getty.edu%2Fulan%2F500010654.

Search Link : https://artresearch.net/resource/?selectedTab=Artists&withimages=false&keyword=michelangelo+buonarotti&uri=Default%3ASearchSimple&semanticSearch=N4IgZiBcDaC6A0IBOBTAzgVwDYBcrAF9EATAQx1LRRzSjkVKwEsBzAOwFsU29JQAVKCAAi5UgDoAsqQCeAIxQhEANXwEiIFklIAHABYBlAMYB7HSgMpSSI3vwhBkEWKmyFSkKr7qCQA

![image](https://user-images.githubusercontent.com/23557768/132687185-a9cc75a9-50e5-49ff-8e1e-c2702886a027.png)

**Comment by lklic** [comment]
this is now resolved....
